name: Android Tests Workflow

on:
  workflow_dispatch:

jobs:
  android-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '34'
          adb-version: latest
          ndk-version: latest
          build-tools-version: '34.0.0'

      - name: List SDK Contents
        run: |
          echo "Listing SDK contents:"
          ls -R $ANDROID_HOME

      - name: Create and Start Android Emulator
        uses: android-actions/start-emulator@v3
        with:
          avd-name: github-actions-emulator
          emulator-options: '-no-window -gpu swiftshader -no-audio'
          disable-animations: true
          ports: 4723
          script: |
            echo "Waiting for emulator..."
            adb wait-for-emulator
            adb shell input keyevent 82 # Unlock screen (KEYCODE_MENU)
        timeout-minutes: 15

      - name: Install Appium
        run: sudo npm install -g appium

      - name: Start Appium Server
        run: appium --log-level debug --port 4723 &
        continue-on-error: true

      - name: Wait for Appium Server
        run: sleep 5

      - name: Build and Test with Maven
        run: mvn clean test -Dsurefire.suiteXmlFile=src/test/TestSuites/GithubActions.xml
        continue-on-error: true

      - name: Create Allure Environment Properties
        run: |
          echo "environment=github-actions" > target/allure-results/environment.properties

      - name: Generate Allure Report
        run: allure generate target/allure-results --clean -o target/allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report
          retention-days: 5